# { "Depends": "py-genlayer:5jycge4q8k23462jtb0b9fyey1s9qz928sz2nbrd9mg4sxqg2qng" }
"""
DATUM -- settles one question on-chain: did a named instrument at a named
official station, over a locked window, clear a locked threshold?

"Official station observation at locked publishers for this window."

GenLayer owns the contested part: official station id (never a free-text
nickname), a completed observation (never a forecast), product status
(FINAL vs PRELIMINARY per this event's own locked constitution), a
timestamp inside the locked window, a matching unit, and two independent
publishers agreeing within a locked tolerance.

Code owns the comparison. The leader's JSON envelope carries a *proposed*
verdict/code alongside structured per-publisher source data -- but that
proposed verdict is NEVER trusted blindly. `datum_lib.evaluate_envelope`
independently re-derives verdict/code from the structured source rows and
only accepts the envelope when the leader's claim matches the derivation
exactly. See contracts/datum_lib.py (zero genlayer imports, plain-pytest
unit-testable) for every rule this file enforces.

Studio Dev only (chain id 61997). State may reset.

This single file is what Studio actually receives -- sibling imports are
not supported by contract validation, so scripts/build_bundle.py inlines
this module's own copy of datum_lib.py's logic below the marker line. Do
not hand-edit the generated bundle; edit contracts/datum_lib.py and
contracts/Datum.py and re-run the bundler. contracts/Datum.py itself is
kept import-free of datum_lib during development (see the DATUM_LIB_SOURCE
marker) so this file lints/tests standalone whenever the bundler has
already run at least once.
"""

import json
from datetime import datetime, timezone

import genlayer as gl
from genlayer.types import *
from genlayer.storage import TreeMap

# ===========================================================================
# BEGIN DATUM_LIB INLINE (generated by scripts/build_bundle.py -- do not
# hand-edit this block; edit contracts/datum_lib.py and re-run the bundler)
# ===========================================================================
# ===========================================================================
# END DATUM_LIB INLINE
# ===========================================================================


# ---------------------------------------------------------------------------
# Deterministic transaction-time clock.
#
# datetime.now() is explicitly sanctioned as deterministic in GenLayer
# contracts (confirmed against genvm-linter's own safety.py exclusion list,
# which forbids time.time()/uuid.uuid4() but not datetime.now()). Used for
# every window/lead/stall/recovery comparison in this contract.
# ---------------------------------------------------------------------------


def _now_ts() -> int:
    return int(datetime.now(timezone.utc).timestamp())


def _addr(a) -> str:
    return str(a)


def _sender() -> str:
    return str(gl.message.sender_address)


# ---------------------------------------------------------------------------
# Events (indexed logs -- not consensus state)
# ---------------------------------------------------------------------------


class EventCreated(gl.chain.Event):
    def __init__(self, event_id: str, creator: Address, instrument_class: str, /): ...


class EventAccepted(gl.chain.Event):
    def __init__(self, event_id: str, acceptor: Address, side: str, /): ...


class EventAdjudicated(gl.chain.Event):
    def __init__(self, event_id: str, verdict: str, code: str, /): ...


class EventFinalized(gl.chain.Event):
    def __init__(self, event_id: str, verdict: str, /): ...


class EventCanceled(gl.chain.Event):
    def __init__(self, event_id: str, /): ...


class EventExpired(gl.chain.Event):
    def __init__(self, event_id: str, /): ...


class EventAppealed(gl.chain.Event):
    def __init__(self, event_id: str, appellant: Address, ground: str, /): ...


class EventLapsedAppeal(gl.chain.Event):
    def __init__(self, event_id: str, /): ...


class Claimed(gl.chain.Event):
    def __init__(self, event_id: str, claimant: Address, amount: u256, /): ...


class RefundRecovered(gl.chain.Event):
    def __init__(self, event_id: str, /): ...


# ---------------------------------------------------------------------------
# Contract
# ---------------------------------------------------------------------------


class Datum(gl.contract.Contract):
    events: TreeMap[str, str]
    creator_open_count: TreeMap[str, u256]
    address_events: TreeMap[str, str]  # address -> json list[event_id]
    claimable: TreeMap[str, u256]  # address -> owed balance
    event_counter: u256
    treasury: str  # constructor-immutable; fees/forfeitures credit here via claim()

    def __init__(self, treasury: str):
        self.treasury = treasury

    # -----------------------------------------------------------------
    # internal helpers
    # -----------------------------------------------------------------

    def _load_event(self, event_id: str) -> dict:
        raw = self.events.get(event_id)
        if raw is None:
            raise gl.vm.UserError(USER_ERRORS["NOT_FOUND"])
        return json.loads(raw)

    def _save_event(self, event_id: str, rec: dict) -> None:
        self.events[event_id] = json.dumps(rec)

    def _touch_address_index(self, addr: str, event_id: str) -> None:
        raw = self.address_events.get(addr)
        ids = json.loads(raw) if raw else []
        if event_id not in ids:
            ids.append(event_id)
        self.address_events[addr] = json.dumps(ids)

    def _credit(self, addr: str, amount: int) -> None:
        if amount <= 0:
            return
        current = int(self.claimable.get(addr, u256(0)))
        self.claimable[addr] = u256(current + amount)

    def _open_count(self, addr: str) -> int:
        return int(self.creator_open_count.get(addr, u256(0)))

    def _bump_open_count(self, addr: str, delta: int) -> None:
        current = self._open_count(addr)
        new_val = max(0, current + delta)
        self.creator_open_count[addr] = u256(new_val)

    # -----------------------------------------------------------------
    # create_event
    # -----------------------------------------------------------------
    @gl.public.write.payable
    def create_event(self, constitution_json: str, side: str, stake: str) -> str:
        """Creates a new event. Attached GEN (gl.message.value) must equal
        stake + CREATE_BOND exactly. `constitution_json` decodes to the
        frozen constitution fields (see datum_lib.validate_constitution).
        `side` is "YES" or "NO" -- the creator's own position. `stake` is a
        decimal-string GEN amount (avoids float/JSON-number precision loss)
        and must fall within [MIN_BET, MAX_BET]."""
        creator = _sender()
        try:
            payload = json.loads(constitution_json)
        except (json.JSONDecodeError, TypeError):
            raise gl.vm.UserError("malformed constitution_json")

        if side not in ("YES", "NO"):
            raise gl.vm.UserError("side must be YES or NO")
        try:
            stake_amount = int(stake)
        except (TypeError, ValueError):
            raise gl.vm.UserError(USER_ERRORS["STAKE_MISMATCH"])

        validate_stake(stake_amount)

        now_ts = _now_ts()
        open_count = self._open_count(creator)
        try:
            validate_constitution(payload, now_ts=now_ts, open_count_for_creator=open_count)
        except DatumValidationError as exc:
            raise gl.vm.UserError(exc.code)

        attached = int(gl.message.value)
        required = stake_amount + CREATE_BOND
        if attached != required:
            raise gl.vm.UserError(USER_ERRORS["STAKE_MISMATCH"])

        instrument_class = payload["class"]
        tolerance = effective_tolerance(instrument_class, payload.get("tolerance"))
        commitment = constitution_commitment(payload)

        event_id = f"{int(self.event_counter):012d}"
        self.event_counter = u256(int(self.event_counter) + 1)

        rec = {
            "id": event_id,
            "creator": creator,
            "created_at": now_ts,
            "state": "OPEN",
            "class": instrument_class,
            "station_id": payload.get("station_id"),
            "bbox": payload.get("bbox"),
            "depth": payload.get("depth"),
            "metric": payload["metric"],
            "threshold": payload["threshold"],
            "cmp": payload["cmp"],
            "window": [int(payload["window"][0]), int(payload["window"][1])],
            "publishers": sorted(dict.fromkeys(payload["publishers"])),
            "product_status_policy": payload.get("product_status_policy", "FINAL_ONLY"),
            "tolerance": tolerance,
            "appeal_window": payload.get("appeal_window", APPEAL_WINDOW_MIN),
            "constitution_hash": commitment,
            "creator_side": side,
            "creator_stake": stake_amount,
            "acceptor": None,
            "acceptor_side": None,
            "acceptor_stake": None,
            "create_bond": CREATE_BOND,
            "create_bond_slashed": False,
            "adjudicate_bond_payer": None,
            "adjudicate_bond": None,
            "verdict": None,
            "code": None,
            "agreed_value": None,
            "accepted_record": None,
            "finalized_at": None,
            "appeal": None,
            "last_state_change_at": now_ts,
            "claims": {},
        }
        self._save_event(event_id, rec)
        self._bump_open_count(creator, +1)
        self._touch_address_index(creator, event_id)
        EventCreated(event_id, gl.message.sender_address, instrument_class).emit()
        return event_id

    # -----------------------------------------------------------------
    # accept_event
    # -----------------------------------------------------------------
    @gl.public.write.payable
    def accept_event(self, event_id: str, side: str) -> None:
        """Single counterparty accepts the opposite side, staking an amount
        equal to the creator's own stake (symmetric 1:1 wager). Moves the
        event OPEN -> ACTIVE."""
        rec = self._load_event(event_id)
        if rec["state"] != "OPEN":
            raise gl.vm.UserError(USER_ERRORS["NOT_OPEN"])
        if rec["acceptor"] is not None:
            raise gl.vm.UserError(USER_ERRORS["ALREADY_ACCEPTED"])
        if side not in ("YES", "NO") or side == rec["creator_side"]:
            raise gl.vm.UserError("side must be the opposite of the creator's side")

        acceptor = _sender()
        attached = int(gl.message.value)
        if attached != rec["creator_stake"]:
            raise gl.vm.UserError(USER_ERRORS["STAKE_MISMATCH"])

        rec["acceptor"] = acceptor
        rec["acceptor_side"] = side
        rec["acceptor_stake"] = attached
        rec["state"] = "ACTIVE"
        rec["last_state_change_at"] = _now_ts()
        self._save_event(event_id, rec)
        self._touch_address_index(acceptor, event_id)
        EventAccepted(event_id, gl.message.sender_address, side).emit()

    # -----------------------------------------------------------------
    # adjudicate
    # -----------------------------------------------------------------
    @gl.public.write.payable
    def adjudicate(self, event_id: str) -> str:
        """Runs the single non-deterministic equivalence check once the
        event's window has closed. Attached GEN must equal ADJUDICATE_BOND
        exactly. Returns the resulting verdict as a string."""
        rec = self._load_event(event_id)
        if rec["state"] != "ACTIVE":
            raise gl.vm.UserError(USER_ERRORS["NOT_OPEN"])
        now_ts = _now_ts()
        if now_ts < rec["window"][1]:
            raise gl.vm.UserError(USER_ERRORS["WINDOW_NOT_CLOSED"])

        attached = int(gl.message.value)
        if attached != ADJUDICATE_BOND:
            raise gl.vm.UserError(USER_ERRORS["STAKE_MISMATCH"])

        adjudicator = _sender()

        # Plain local copies -- the ONLY values the nondet closures see.
        instrument_class = rec["class"]
        station_id = rec["station_id"]
        bbox = rec["bbox"]
        depth = rec.get("depth")
        window = tuple(rec["window"])
        policy = rec["product_status_policy"]
        publishers = list(rec["publishers"])
        event_id_local = event_id

        def leader_fn() -> str:
            envelope = gl.nondet.exec_prompt(
                _adjudication_prompt(
                    instrument_class=instrument_class,
                    station_id=station_id,
                    bbox=bbox,
                    depth=depth,
                    window=window,
                    policy=policy,
                    publishers=publishers,
                    event_id=event_id_local,
                )
            )
            return envelope

        def validator_fn(leader_result) -> bool:
            # Never validate the leader's own claimed output structurally
            # only -- re-acquire the evidence independently (re-run
            # leader_fn from scratch: a fresh gl.nondet.exec_prompt call,
            # not a re-read of leader_result) and compare the two
            # independently-derived outcomes. A leader that fabricated a
            # self-consistent-but-fictional envelope would pass a
            # structural-only check; it cannot pass this one unless this
            # validator's own independent fetch agrees.
            try:
                leader_envelope = json.loads(str(leader_result))
            except (json.JSONDecodeError, TypeError):
                return False

            my_raw = leader_fn()
            try:
                my_envelope = json.loads(str(my_raw))
            except (json.JSONDecodeError, TypeError):
                return False

            leader_eval = evaluate_envelope(
                instrument_class=instrument_class,
                expected_station_id=station_id,
                expected_bbox=bbox,
                window=window,
                product_status_policy=policy,
                tolerance_scaled=rec["tolerance"],
                threshold_scaled=rec["threshold"],
                cmp_op=rec["cmp"],
                envelope=leader_envelope,
            )
            my_eval = evaluate_envelope(
                instrument_class=instrument_class,
                expected_station_id=station_id,
                expected_bbox=bbox,
                window=window,
                product_status_policy=policy,
                tolerance_scaled=rec["tolerance"],
                threshold_scaled=rec["threshold"],
                cmp_op=rec["cmp"],
                envelope=my_envelope,
            )
            if not leader_eval["accepted"] or not my_eval["accepted"]:
                return False
            return (
                leader_eval["verdict"] == my_eval["verdict"]
                and leader_eval["code"] == my_eval["code"]
                and leader_eval["agreed_value"] == my_eval["agreed_value"]
            )

        raw_envelope = gl.vm.run_nondet(leader_fn, validator_fn)

        try:
            envelope = json.loads(str(raw_envelope))
        except (json.JSONDecodeError, TypeError):
            envelope = {}

        evaluation = evaluate_envelope(
            instrument_class=instrument_class,
            expected_station_id=station_id,
            expected_bbox=bbox,
            window=window,
            product_status_policy=policy,
            tolerance_scaled=rec["tolerance"],
            threshold_scaled=rec["threshold"],
            cmp_op=rec["cmp"],
            envelope=envelope,
        )

        if not evaluation["accepted"]:
            # On reject/exception: do not move pools. Bond is simply held
            # in the contract until reclaim_bonds/finalize sorts it out --
            # here we return it immediately since nothing was settled.
            self._credit(adjudicator, ADJUDICATE_BOND)
            rec["last_state_change_at"] = _now_ts()
            self._save_event(event_id, rec)
            return "REJECTED"

        rec["verdict"] = evaluation["verdict"]
        rec["code"] = evaluation["code"]
        rec["agreed_value"] = evaluation["agreed_value"]
        rec["accepted_record"] = {
            pub: {"usable": ok, "reason": reason, "converted": converted}
            for pub, (ok, reason, converted) in evaluation["validated_sources"].items()
        }
        rec["adjudicate_bond_payer"] = adjudicator
        rec["adjudicate_bond"] = ADJUDICATE_BOND
        rec["state"] = "VERDICT_PENDING"
        rec["last_state_change_at"] = _now_ts()
        self._save_event(event_id, rec)
        EventAdjudicated(event_id, rec["verdict"], rec["code"]).emit()
        return rec["verdict"]

    # -----------------------------------------------------------------
    # finalize
    # -----------------------------------------------------------------
    @gl.public.write
    def finalize(self, event_id: str) -> None:
        """Finalizes a VERDICT_PENDING event once its appeal window has
        elapsed with no appeal. Settles the pot per the recorded verdict."""
        rec = self._load_event(event_id)
        if rec["state"] != "VERDICT_PENDING":
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])
        now_ts = _now_ts()
        if now_ts < rec["last_state_change_at"] + rec["appeal_window"]:
            raise gl.vm.UserError(USER_ERRORS["APPEAL_CLOSED"])
        self._settle(event_id, rec, now_ts)

    def _settle(self, event_id: str, rec: dict, now_ts: int) -> None:
        creator = rec["creator"]
        acceptor = rec["acceptor"]
        creator_side = rec["creator_side"]
        acceptor_side = rec["acceptor_side"]
        creator_stake = rec["creator_stake"]
        acceptor_stake = rec["acceptor_stake"] or 0
        pot = creator_stake + acceptor_stake
        adjudicator = rec.get("adjudicate_bond_payer")
        adjudicate_bond = rec.get("adjudicate_bond") or 0

        # CREATE_BOND is only ever at risk of slashing via expire_event()
        # (window opened with no acceptor). Once an event reaches _settle()
        # at all, an acceptor existed -- the creator held up their end, so
        # their bond returns here regardless of the eventual verdict.
        if not rec.get("create_bond_slashed"):
            self._credit(creator, rec["create_bond"])

        if rec["verdict"] == "INCONCLUSIVE":
            # deterministic refund path -- zero fee, bond returned.
            self._credit(creator, creator_stake)
            if acceptor:
                self._credit(acceptor, acceptor_stake)
            if adjudicator:
                self._credit(adjudicator, adjudicate_bond)
        else:
            winner_addr = creator if creator_side == rec["verdict"] else acceptor
            fee_total, adj_share, treasury_share = decisive_fee(pot)
            pot_after_fee = pot - fee_total
            self._credit(winner_addr, pot_after_fee)
            if adjudicator:
                self._credit(adjudicator, adjudicate_bond + adj_share)
            self._credit(self.treasury, treasury_share)

        # An appeal bond is only ever collected on the way INTO this state
        # (appeal() -> re_adjudicate() -> here); resolve it now rather than
        # leaving it stranded in the contract with no ledger entry at all.
        # Refund the appellant if the appeal changed the outcome (they were
        # right to appeal); forfeit to treasury if it didn't -- same rule
        # lapse_appeal() already applies for a stalled appeal.
        appeal = rec.get("appeal")
        if appeal:
            if rec["verdict"] != appeal["prior_verdict"]:
                self._credit(appeal["appellant"], appeal["bond"])
            else:
                self._credit(self.treasury, appeal["bond"])
            rec["appeal"] = None

        rec["state"] = "FINALIZED"
        rec["finalized_at"] = now_ts
        rec["last_state_change_at"] = now_ts
        self._save_event(event_id, rec)
        self._bump_open_count(creator, -1)
        EventFinalized(event_id, rec["verdict"] or "INCONCLUSIVE").emit()

    # -----------------------------------------------------------------
    # appeal / re_adjudicate / lapse_appeal
    # -----------------------------------------------------------------
    @gl.public.write.payable
    def appeal(self, event_id: str, ground: str) -> None:
        """Any bonded party (creator or acceptor) may appeal a
        VERDICT_PENDING event within its appeal window, posting
        APPEAL_BOND (half of one side's stake, floor 0.05 GEN)."""
        rec = self._load_event(event_id)
        if rec["state"] != "VERDICT_PENDING":
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])
        if ground not in VALID_APPEAL_GROUNDS:
            raise gl.vm.UserError("unknown appeal ground")
        now_ts = _now_ts()
        if now_ts >= rec["last_state_change_at"] + rec["appeal_window"]:
            raise gl.vm.UserError(USER_ERRORS["APPEAL_CLOSED"])

        sender = _sender()
        if sender not in (rec["creator"], rec["acceptor"]):
            raise gl.vm.UserError(USER_ERRORS["NOT_A_PARTY"])

        bond = appeal_bond_amount(rec["creator_stake"])
        attached = int(gl.message.value)
        if attached != bond:
            raise gl.vm.UserError(USER_ERRORS["STAKE_MISMATCH"])

        rec["appeal"] = {
            "appellant": sender,
            "ground": ground,
            "bond": bond,
            "opened_at": now_ts,
            "prior_verdict": rec["verdict"],
            "prior_code": rec["code"],
        }
        rec["state"] = "APPEALED"
        rec["last_state_change_at"] = now_ts
        self._save_event(event_id, rec)
        EventAppealed(event_id, gl.message.sender_address, ground).emit()

    @gl.public.write.payable
    def re_adjudicate(self, event_id: str) -> str:
        """Re-runs adjudication for an APPEALED event. VALUE/STATION/
        WINDOW/STATUS grounds re-read the already-stored constitution
        (never blurring the prior locked fields); REVISED may live-refresh
        source data but still runs through the same code-side acceptance
        gate as the original adjudicate()."""
        rec = self._load_event(event_id)
        if rec["state"] != "APPEALED":
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])

        # The ORIGINAL adjudicator's bond is about to be overwritten by
        # whoever calls adjudicate() again below -- credit it back now,
        # or it is silently lost with no ledger entry at all (it is not
        # the appeal bond, which is resolved separately in _settle()).
        prior_payer = rec.get("adjudicate_bond_payer")
        prior_bond = rec.get("adjudicate_bond") or 0
        if prior_payer and prior_bond:
            self._credit(prior_payer, prior_bond)

        rec["state"] = "ACTIVE"
        rec["adjudicate_bond_payer"] = None
        rec["adjudicate_bond"] = None
        self._save_event(event_id, rec)

        # Reuse the ordinary adjudicate() path -- appeal bond stays held
        # until finalize() resolves who was right (see _settle's appeal
        # bond handling below, folded into the next finalize()).
        return self.adjudicate(event_id)

    @gl.public.write
    def lapse_appeal(self, event_id: str) -> None:
        """If an APPEALED event stalls (no re_adjudicate) for
        LAPSE_APPEAL_STALL, anyone may restore the prior verdict and move
        the event back to VERDICT_PENDING so finalize() can proceed."""
        rec = self._load_event(event_id)
        if rec["state"] != "APPEALED":
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])
        now_ts = _now_ts()
        appeal = rec["appeal"]
        if now_ts < appeal["opened_at"] + LAPSE_APPEAL_STALL:
            raise gl.vm.UserError("appeal has not stalled yet")

        rec["verdict"] = appeal["prior_verdict"]
        rec["code"] = appeal["prior_code"]
        # appellant's bond is forfeit to treasury for failing to follow
        # through on their own appeal.
        self._credit(self.treasury, appeal["bond"])
        rec["appeal"] = None
        rec["state"] = "VERDICT_PENDING"
        rec["last_state_change_at"] = now_ts
        self._save_event(event_id, rec)
        EventLapsedAppeal(event_id).emit()

    # -----------------------------------------------------------------
    # cancel_event / expire_event
    # -----------------------------------------------------------------
    @gl.public.write
    def cancel_event(self, event_id: str) -> None:
        """Creator may cancel their own event before anyone accepts it.
        Full refund of stake + create bond."""
        rec = self._load_event(event_id)
        if rec["state"] != "OPEN":
            raise gl.vm.UserError(USER_ERRORS["NOT_OPEN"])
        if _sender() != rec["creator"]:
            raise gl.vm.UserError(USER_ERRORS["NOT_A_PARTY"])

        self._credit(rec["creator"], rec["creator_stake"] + rec["create_bond"])
        rec["state"] = "CANCELED"
        rec["last_state_change_at"] = _now_ts()
        self._save_event(event_id, rec)
        self._bump_open_count(rec["creator"], -1)
        EventCanceled(event_id).emit()

    @gl.public.write
    def expire_event(self, event_id: str) -> None:
        """Anyone may expire an OPEN event once its window has started
        with no acceptor. Creator's stake is refunded; the CREATE_BOND is
        slashed to the treasury as the cost of an unaccepted claim."""
        rec = self._load_event(event_id)
        if rec["state"] != "OPEN":
            raise gl.vm.UserError(USER_ERRORS["NOT_OPEN"])
        now_ts = _now_ts()
        if now_ts < rec["window"][0]:
            raise gl.vm.UserError("window has not started yet")

        self._credit(rec["creator"], rec["creator_stake"])
        self._credit(self.treasury, rec["create_bond"])
        rec["create_bond_slashed"] = True
        rec["state"] = "EXPIRED"
        rec["last_state_change_at"] = now_ts
        self._save_event(event_id, rec)
        self._bump_open_count(rec["creator"], -1)
        EventExpired(event_id).emit()

    # -----------------------------------------------------------------
    # recover_refund / reclaim_bonds
    # -----------------------------------------------------------------
    @gl.public.write
    def recover_refund(self, event_id: str) -> None:
        """Deterministic fallback: if an ACTIVE/VERDICT_PENDING/APPEALED
        event has sat without reaching FINALIZED for RECOVER_REFUND_AFTER,
        anyone may force a no-fee refund of both stakes (and any posted
        bonds) without needing matching evidence."""
        rec = self._load_event(event_id)
        if rec["state"] not in ("ACTIVE", "VERDICT_PENDING", "APPEALED"):
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])
        now_ts = _now_ts()
        if now_ts < rec["window"][1] + RECOVER_REFUND_AFTER:
            raise gl.vm.UserError("recovery window not reached")

        self._credit(rec["creator"], rec["creator_stake"])
        if rec["acceptor"]:
            self._credit(rec["acceptor"], rec["acceptor_stake"] or 0)
        if rec.get("adjudicate_bond_payer"):
            self._credit(rec["adjudicate_bond_payer"], rec.get("adjudicate_bond") or 0)
        if rec.get("appeal"):
            self._credit(rec["appeal"]["appellant"], rec["appeal"]["bond"])

        rec["state"] = "FINALIZED"
        rec["verdict"] = "INCONCLUSIVE"
        rec["code"] = "MISSING"
        rec["finalized_at"] = now_ts
        rec["last_state_change_at"] = now_ts
        self._save_event(event_id, rec)
        self._bump_open_count(rec["creator"], -1)
        RefundRecovered(event_id).emit()

    @gl.public.write
    def reclaim_bonds(self, event_id: str) -> None:
        """Sweeps any bond amounts left un-credited on a FINALIZED/
        CANCELED/EXPIRED event back to their payer (idempotent no-op if
        nothing is left -- raises nothing_to_claim only if the caller has
        no stake in this event at all)."""
        rec = self._load_event(event_id)
        if rec["state"] not in ("FINALIZED", "CANCELED", "EXPIRED"):
            raise gl.vm.UserError(USER_ERRORS["NOT_PENDING"])
        sender = _sender()
        parties = {rec["creator"], rec.get("acceptor"), rec.get("adjudicate_bond_payer")}
        appeal = rec.get("appeal")
        if appeal:
            parties.add(appeal.get("appellant"))
        if sender not in parties:
            raise gl.vm.UserError(USER_ERRORS["NOTHING_TO_CLAIM"])
        # All bond/stake movement already happened in _settle/expire_event/
        # recover_refund's _credit() calls; this is a documented no-op
        # confirmation endpoint for UIs that want an explicit receipt.
        return None

    # -----------------------------------------------------------------
    # claim
    # -----------------------------------------------------------------
    @gl.public.write
    def claim(self, event_id: str) -> u256:
        """The only method that moves GEN out of the contract. Pays the
        caller's full claimable balance credited across every event they
        have touched (event_id is accepted for API-symmetry / UI receipts
        but the payout itself is the caller's whole ledger balance, so the
        last claimant of a multi-party pot never gets stranded by dust)."""
        _ = self._load_event(event_id)  # validates the event exists
        sender = _sender()
        owed = int(self.claimable.get(sender, u256(0)))
        if owed <= 0:
            raise gl.vm.UserError(USER_ERRORS["NOTHING_TO_CLAIM"])

        self.claimable[sender] = u256(0)
        gl.contract.get_at(gl.message.sender_address).emit_transfer(value=u256(owed))
        Claimed(event_id, gl.message.sender_address, u256(owed)).emit()
        return u256(owed)

    # -----------------------------------------------------------------
    # views
    # -----------------------------------------------------------------
    @gl.public.view
    def get_constitution(self, event_id: str) -> str:
        rec = self._load_event(event_id)
        return json.dumps(
            {
                "class": rec["class"],
                "station_id": rec["station_id"],
                "bbox": rec["bbox"],
                "depth": rec["depth"],
                "metric": rec["metric"],
                "threshold": rec["threshold"],
                "cmp": rec["cmp"],
                "window": rec["window"],
                "publishers": rec["publishers"],
                "product_status_policy": rec["product_status_policy"],
                "tolerance": rec["tolerance"],
                "constitution_hash": rec["constitution_hash"],
            }
        )

    @gl.public.view
    def get_config(self) -> str:
        return json.dumps(
            {
                "chain_id": 61997,
                "network": "studio-dev",
                "value_scale": VALUE_SCALE,
                "min_bet": str(MIN_BET),
                "max_bet": str(MAX_BET),
                "create_bond": str(CREATE_BOND),
                "adjudicate_bond": str(ADJUDICATE_BOND),
                "fee_bps": FEE_BPS,
                "appeal_bond_floor": str(APPEAL_BOND_FLOOR),
                "appeal_window_min": APPEAL_WINDOW_MIN,
                "appeal_window_max": APPEAL_WINDOW_MAX,
                "lapse_appeal_stall": LAPSE_APPEAL_STALL,
                "recover_refund_after": RECOVER_REFUND_AFTER,
                "max_open_per_creator": MAX_OPEN_PER_CREATOR,
                "max_page_size": MAX_PAGE_SIZE,
                "state_may_reset": True,
            }
        )

    @gl.public.view
    def get_registry(self) -> str:
        return json.dumps(
            {
                "publishers": PUBLISHER_REGISTRY,
                "class_min_window": CLASS_MIN_WINDOW,
                "class_unit": CLASS_UNIT,
                "class_metrics": CLASS_METRICS,
                "class_default_tolerance": CLASS_DEFAULT_TOLERANCE,
            }
        )

    @gl.public.view
    def get_event(self, event_id: str) -> str:
        return json.dumps(self._load_event(event_id))

    @gl.public.view
    def get_board(self, cursor: u256, limit: u256, state_filter: str) -> str:
        all_ids = list(self.events.keys())
        if state_filter:
            filtered = []
            for eid in all_ids:
                rec = json.loads(self.events[eid])
                if rec["state"] == state_filter:
                    filtered.append(eid)
            all_ids = filtered
        page_ids, next_cursor = paginate(all_ids, int(cursor), int(limit))
        rows = [json.loads(self.events[eid]) for eid in page_ids]
        return json.dumps({"rows": rows, "next_cursor": next_cursor})

    @gl.public.view
    def get_record(self, event_id: str) -> str:
        rec = self._load_event(event_id)
        return json.dumps(
            {
                "verdict": rec["verdict"],
                "code": rec["code"],
                "agreed_value": rec["agreed_value"],
                "accepted_record": rec["accepted_record"],
                "state": rec["state"],
            }
        )

    @gl.public.view
    def get_position(self, event_id: str, address: str) -> str:
        rec = self._load_event(event_id)
        addr = address
        side = None
        stake = None
        if addr == rec["creator"]:
            side, stake = rec["creator_side"], rec["creator_stake"]
        elif addr == rec.get("acceptor"):
            side, stake = rec["acceptor_side"], rec["acceptor_stake"]
        return json.dumps({"event_id": event_id, "address": addr, "side": side, "stake": stake})

    @gl.public.view
    def get_positions(self, address: str, cursor: u256, limit: u256) -> str:
        raw = self.address_events.get(address)
        ids = json.loads(raw) if raw else []
        page_ids, next_cursor = paginate(ids, int(cursor), int(limit))
        rows = []
        for eid in page_ids:
            rec = json.loads(self.events[eid])
            side = None
            stake = None
            if address == rec["creator"]:
                side, stake = rec["creator_side"], rec["creator_stake"]
            elif address == rec.get("acceptor"):
                side, stake = rec["acceptor_side"], rec["acceptor_stake"]
            rows.append({"event_id": eid, "side": side, "stake": stake, "state": rec["state"]})
        return json.dumps({"rows": rows, "next_cursor": next_cursor})

    @gl.public.view
    def get_claimable(self, address: str, cursor: u256, limit: u256) -> str:
        owed = int(self.claimable.get(address, u256(0)))
        return json.dumps({"address": address, "claimable": str(owed)})

    @gl.public.view
    def get_activity(self, address: str, cursor: u256, limit: u256) -> str:
        raw = self.address_events.get(address)
        ids = json.loads(raw) if raw else []
        page_ids, next_cursor = paginate(ids, int(cursor), int(limit))
        rows = [json.loads(self.events[eid]) for eid in page_ids]
        return json.dumps({"rows": rows, "next_cursor": next_cursor})
